In [1]:
import numpy as np

In [2]:
mx_1s=np.array([[1,1,1],[1,1,1],[1,1,1]])

In [3]:
mx_1s=np.ones(5)

array([1., 1., 1., 1., 1.])

In [4]:
print(mx_1s)

[[1 1 1]
 [1 1 1]
 [1 1 1]]


In [5]:
mx_1s.dtype

dtype('int32')

In [6]:
mx_1s=np.ones((3,4))
print(mx_1s)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [8]:
mx_1s=np.ones((3,4),dtype=int)
print(mx_1s)

[[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]]


In [10]:
mx_0s = np.zeros((4,6),dtype=bool)
print(mx_0s)

[[False False False False False False]
 [False False False False False False]
 [False False False False False False]
 [False False False False False False]]


In [11]:
mx_0s = np.zeros((4,6),dtype=str)
print(mx_0s)

[['' '' '' '' '' '']
 ['' '' '' '' '' '']
 ['' '' '' '' '' '']
 ['' '' '' '' '' '']]


In [13]:
em_mx=np.empty((3,3))
print(em_mx)

[[0.00000000e+000 0.00000000e+000 0.00000000e+000]
 [0.00000000e+000 0.00000000e+000 6.06712613e-321]
 [7.56593016e-307 3.11521884e-307 3.72363246e-317]]
