Numpy functions

In [1]:
import numpy as np

In [2]:
arr_1d=np.arange(1,13)

In [3]:
print(arr_1d)

[ 1  2  3  4  5  6  7  8  9 10 11 12]


In [8]:
arr_1d=np.arange(1,13)
print(arr_1d)

[ 1  2  3  4  5  6  7  8  9 10 11 12]


In [9]:
arr_even=np.arange(1,13,2)
print(arr_even)

[ 1  3  5  7  9 11]


In [10]:
np.linspace(1,5,4)
#4 value from range 1 to 5

array([1.        , 2.33333333, 3.66666667, 5.        ])

In [13]:
arr_2d=arr_1d.reshape(3,4)
print(arr_2d) #product of both the parameters in reshape function should be equal to size of the matrice that is to be concerted to 2d

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [14]:
arr_3d=arr_1d.reshape(2,3,2)
#dot product of all three parameters should be equal to the size of the array that is to be converted to 3d
print(arr_3d)

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]


In [17]:
 m1=np.arange(1,13).reshape(3,4)
print(m1)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [18]:
m1.ravel()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [19]:
m1.flatten()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [20]:
m1.transpose()

array([[ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11],
       [ 4,  8, 12]])