In [1]:
import numpy as np
import random 

In [4]:
np.random.random(1)

array([0.11240211])

In [5]:
 np.random.random((3,3))

array([[0.23071478, 0.9166667 , 0.22494311],
       [0.61969626, 0.37873564, 0.46768754],
       [0.63854604, 0.51828506, 0.36634459]])

In [6]:
np.random.randint(1,4)

3

In [7]:
np.random.randint(1,4,(4,4))

array([[1, 1, 1, 2]])

In [8]:
np.random.randint(1,4,(2,4,4)) 

array([[[1, 3, 1, 3],
        [3, 3, 1, 2],
        [3, 3, 1, 3],
        [2, 1, 2, 3]],

       [[1, 1, 2, 1],
        [3, 3, 2, 2],
        [1, 2, 2, 3],
        [3, 1, 1, 2]]])

In [9]:
np.random.seed(10)
np.random.randint(1,4,(2,4,4))

array([[[2, 2, 1, 1],
        [2, 1, 2, 2],
        [1, 2, 2, 3],
        [1, 2, 1, 3]],

       [[1, 3, 1, 1],
        [1, 3, 1, 3],
        [3, 2, 1, 1],
        [3, 2, 3, 2]]])

In [10]:
np.random.seed(10)
np.random.randint(1,4,(2,4,4))

array([[[2, 2, 1, 1],
        [2, 1, 2, 2],
        [1, 2, 2, 3],
        [1, 2, 1, 3]],

       [[1, 3, 1, 1],
        [1, 3, 1, 3],
        [3, 2, 1, 1],
        [3, 2, 3, 2]]])

In [11]:
np.random.rand(3)

array([0.13145815, 0.41366737, 0.77872881])

In [12]:
np.random.rand(3,3)

array([[0.58390137, 0.18263144, 0.82608225],
       [0.10540183, 0.28357668, 0.06556327],
       [0.05644419, 0.76545582, 0.01178803]])

In [13]:
np.random.randn(3,3)

array([[-1.58494101,  1.05535316, -1.92657911],
       [ 0.69858388, -0.74620143, -0.15662666],
       [-0.19363594,  1.13912535,  0.36221796]])

In [14]:
x=[1,2,3,4]
np.random.choice(x)

1

In [15]:
np.random.choice(x)

1

In [17]:
for i in range(20):
    print(np.random.choice(x))

3
4
1
1
1
1
3
3
2
2
4
1
1
3
2
2
4
2
3
2


In [18]:
x

[1, 2, 3, 4]

In [19]:
np.random.permutation(x)

array([4, 3, 2, 1])

In [20]:
np.random.permutation(x)

array([4, 3, 1, 2])

In [23]:
print(np.random.shuffle(x))

None
